### ISSUE TITLE
Raster layer doesn't show in plot_map()

### ISSUE THREAD

**Issue by MargotK25** [4DModeller/fdmr#254] opened 2023-11-03 13:50 UTC
**Describe the bug**
When using a raster as input to the `plot_map` function, no errors arise but the raster layer doesn't show. When simply using `plot`, the raster is plotted without any issues.

`plot_map`:
![image](https://github.com/4DModeller/fdmr/assets/100343401/3b0edcf4-3bc3-4aae-a27d-36ba0bc6de84)

`plot`
![image](https://github.com/4DModeller/fdmr/assets/100343401/3f2e069d-0b77-451f-ad4f-78a81ef1c463)

**Expected behavior**
The raster layer showing on top of the basemap.

**User Environment (please complete the following information):**
 - OS: Windows
 - Version of R: 4.3.2
 - Version of fdmr you are using: 0.1.1

**Comment by XueqingYin** [comment] 2023-11-05 11:06
That's weird. Which raster data was used to create the leaflet map above?  I tested the plot_map() with the online raster data oisst-sst.nc (downloaded from https://github.com/rstudio/leaflet/tree/main/docs/nc), and it showed the raster layer.

![image](https://github.com/4DModeller/fdmr/assets/83759494/ce99249c-73b6-489a-a71d-2e2ea988f2e0)

If using the ```plot()```, I got:

![image](https://github.com/4DModeller/fdmr/assets/83759494/b03f75e8-fb32-49e8-8c0b-555aa17e85dc)

**Comment by XueqingYin** [comment] 2023-11-06 16:09
Hi @aabelean, below is the map when using the latest version. 

![image](https://github.com/4DModeller/fdmr/assets/83759494/40f0716f-e77f-42df-9e6c-292af8ef1ca7)

The codes are: 
```
library(raster)
r <- raster("oisst-sst.nc")
plot_map(raster_data =  r)  

```

**Comment by aabelean** [comment] 2023-11-07 17:52
Thanks @XueqingYin.

Margot used this code:
```
load("data/hydro_bru.RData")

temp <- hydro

# shift longitude by 180 such that it ranges from -180 to 180
temp$lon <- temp$lon - 180

# convert the data frame to a spatial object
coordinates(temp) <- ~ lon + lat

# create a raster
ras_dom <- raster()

# convert the point data to a raster with the mean as its values
result <- rasterize(temp, ras_dom, "mean", update = TRUE)

# plot the raster with the mean attribution of hydrology to sea level change on a map
plot_map(raster = result)
```
Technically, the conversion of coordinates is not correct (we get the 0 at international dateline), but it does not really matter for this problem. 

We were working with this file: 
[hydro_bru.zip](https://github.com/4DModeller/fdmr/files/13284196/hydro_bru.zip)

**Comment by XueqingYin** [comment] 2023-11-07 18:29
Thanks @aabelean for providing the codes and data. I ran your codes and the raster layer remained visible. Here is what I got:

![image](https://github.com/4DModeller/fdmr/assets/83759494/206627ae-158a-4a29-8415-34bee5495d37)

**Comment by aabelean** [comment] 2023-11-07 18:33
Thanks for checking @XueqingYin. May I also ask what version of R, leaflet and raster are you using?

**Comment by XueqingYin** [comment] 2023-11-07 18:37
@aabelean , I'm using R version 4.2.1, leaflet version ‘2.1.1’ and raster version ‘3.6.3’.

**Comment by aabelean** [comment] 2023-11-07 18:42
Okay, I'll test on R 4.2 because with R 4.3.1 I also cannot get it work properly.

**Comment by aabelean** [comment] 2023-11-07 23:15
Yes, I could not reproduce this error with R 4.2.0 (raster 3.6-23, leaflet 2,1,2). Attached – the map obtained (I changed the coordinate conversion)
![test_hydro_r_420](https://github.com/4DModeller/fdmr/assets/57137242/95fd81d0-6ab4-4533-ac15-60ee082411da)

I also did not have any issues with plotting SST sample @XueqingYin gave with either R 4.2.0 or R 4.3.1.

**Comment by mnky9800n** [comment] 2023-11-13 09:16
This issue should be closed when we update dependency requirements for R-studio and leaflet

**Comment by gareth-j** [comment] 2023-11-28 10:24
@aabelean can you set some fixed verison dependencies for this? We can test it with the new mapview tool if that PR gets merged.

**Closed** 2023-12-19 11:44 UTC
Labels: plotting, hackathon-23, map
