### ISSUE TITLE
map maker function should be able to accept a trained model as input then map the predicted values or uncertainty values

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#7] opened 2023-04-25 17:22 UTC
One way to check whether a model is producing reasonable results is to look at the spatial distribution of predicted results (or uncertainties) and see if they align with the data being modeled. It would be very nice if the model could accept, in addition to raster, points, and other kinds of data, a trained model that then auto-generates the predicted output for the map and then maps it.

**Comment by gareth-j** [comment] 2023-06-20 15:18
I think this needs discussing and a chunk of work so I'm going to reassign this to the next milestone.

**Comment by gareth-j** [comment] 2023-09-19 10:38
Closing as duplicate of #111

**Closed by gareth-j** 2023-09-19 10:38 UTC
Labels: enhancement
