### ISSUE TITLE
sklearn paradigm function

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#224] opened 2023-10-30 10:54 UTC
Discussing with @gareth-j it seems like the shiny apps are rather instructive but they may not be off the shelf functional without the addition of a sklearn like wrapper.

It would be super nice if there was a function that simply worked like:

```
model <- fdmr::modelFit(kind='lgcp', dataX, dataY, hyperparameters)
modelEval(model)
```

and the function built the finite element mesh, accepted a giant dictionary of ever increasing in complexity hyperparamters htat described the mesh, model priors, etc. but then everything else is the same.

this comes about that if you play around with all of the different sliders and what not, nothing really ever changes a model DIC that much. the thing that changes hte model DIC the most is the introduction of new variables. this makes sense, of course.

the goal here would not be to make a function that makes a perfect model, but simply make one that automates all of the steps such that you could get a good enough model in a single line of code (ala, `sklearn`).

**Comment by gareth-j** [comment] 2023-11-28 10:16
Dupe of #276

**Closed by gareth-j** 2023-11-28 10:16 UTC
Labels: enhancement, release-2, utrecht-sprint
